feat: added environments

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -9,27 +9,74 @@ variables:
   SFTP_PORT: "$SFTP_PORT"
   SFTP_DAGS_PATH: "$SFTP_DAGS_PATH"
 
-quality:
+# Détermination de l'environnement selon gitflow
+before_script:
+  # ENVIRONMENT par défaut
+  - |
+    if [[ "$CI_PIPELINE_SOURCE" == "merge_request_event" && "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "main" ]]; then
+      export ENVIRONMENT=dev
+    elif [[ "$CI_PIPELINE_SOURCE" == "merge_request_event" && "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" == "main" && "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "production" ]]; then
+      export ENVIRONMENT=staging
+    elif [[ "$CI_COMMIT_TAG" != "" && "$CI_COMMIT_REF_PROTECTED" == "true" && "$CI_COMMIT_BRANCH" == "production" ]]; then
+      export ENVIRONMENT=production
+    else # raise an error
+      echo "Error: Unable to determine the environment for deployment."
+      exit 1
+    fi
+    echo "ENVIRONMENT=$ENVIRONMENT"
+
+ruff:
   stage: quality
   image: python:3.12
   script:
     - pip install uv
-    - uvx ruff src/ --output-format=github
+    - uvx ruff check src/ --output-format=github
+  only:
+    - main
+    - merge_requests
+
+mypy:
+  stage: quality
+  image: python:3.12
+  script:
+    - pip install uv
     - uvx mypy src/
+  only:
+    - main
+    - merge_requests
+
+bandit:
+  stage: quality
+  image: python:3.12
+  script:
+    - pip install uv
     - uvx bandit -r src/
-    - uvx ty check
+  only:
+    - main
+    - merge_requests
+
+ty:
+  stage: quality
+  image: python:3.12
+  script:
+    - pip install uv
+    - uvx ty check src/
   only:
     - main
     - merge_requests
 
 publish:
   stage: publish
-  image: atmoz/sftp
-  dependencies:
-    - quality
+  image: alpine:3.18
+  needs:
+    - ruff
+    - mypy
+    - bandit
+    - ty
   script:
     - apk add --no-cache lftp
-    - lftp -u "$SFTP_USERNAME","$SFTP_PASSWORD" -e "mirror -R src $SFTP_DAGS_PATH; bye" -p $SFTP_PORT $SFTP_HOST
+    - lftp -u "$SFTP_USERNAME","$SFTP_PASSWORD" -e "mirror -R src $SFTP_DAGS_PATH/$ENVIRONMENT; bye" -p $SFTP_PORT $SFTP_HOST
   only:
     - main
+    - tags
   when: on_success
